[wechat]
version = "3.9.10.19"
port = "30001"

[wechat_robot]
name = "æ™ºå¾®åŠ©æ‰‹(1.0.1)"
main_height = 1280
main_width = 720
group_switch = 1

[fastapi]
port = "9000"

[group_template]
out_setting = "â•’â•â•â•ã€æˆå‘˜ç¦»åˆ«ã€‘â•â•â•â•—\nğŸ‚ å¯ç¦€ç¾¤ä¸»ï¼Œæœ‰æˆå‘˜ç¦»ç¾¤ğŸš¶â€â™‚ï¸\n     æ˜µç§°ï¼š[name]\nâ•˜â•â•â•ã€æ„Ÿè°¢é™ªä¼´ã€‘â•â•â•â•"
out_setting_tip = "é€€ç¾¤æé†’åªæ”¯æŒæ–‡å­—ã€emojiè¡¨æƒ…,æ¢è¡Œinæˆ–[enterç¾¤ç”¨æˆ·:[name]"
welcome_setting = "â•’â•â•â•ã€æ–°æˆå‘˜æŠ¥åˆ°ã€‘â•â•â•â•—\nğŸ‰ å¯ç¦€ç¾¤ä¸»ï¼Œæ–°æˆå‘˜é©¾åˆ°ï¼ğŸšª\n    æ˜µç§°ï¼š[name]\n    é¢†è·¯äººï¼š[inviter]ğŸ‘«\nâ•˜â•â•â•ã€æ¬¢è¿åŠ å…¥ã€‘â•â•â•â•\n\n ğŸ“åŸºäºå¼€æºé¡¹ç›®:  https://github.com/yxj1028530975/wechat_robot_flet.gitï¼ˆè®°å¾— Star â­ï¸ï¼‰\n"
# welcome_setting = "â•’â•â•â•ã€æ–°æˆå‘˜æŠ¥åˆ°ã€‘â•â•â•â•—\nğŸ‰ å¯ç¦€ç¾¤ä¸»ï¼Œæ–°æˆå‘˜é©¾åˆ°ï¼ğŸšª\n    æ˜µç§°ï¼š[name]\n    é¢†è·¯äººï¼š[inviter]ğŸ‘«\nâ•˜â•â•â•ã€æ¬¢è¿åŠ å…¥ã€‘â•â•â•â•"
welcome_setting_tip = "æ–°äººè¿›ç¾¤æé†’åªæ”¯æŒæ–‡å­—ã€emojiè¡¨æƒ…,æ¢è¡Œinæˆ–[enterç¾¤ç”¨æˆ·:[name]"
fun_setting = "â•’â•â•åŠŸèƒ½æç¤ºâ•â•â•—"
fun_setting_tip = "åŠŸèƒ½æç¤ºåªæ”¯æŒæ–‡å­—ã€emojiè¡¨æƒ…,æ¢è¡Œinæˆ–[enterç¾¤ç”¨æˆ·:[name]"

[wechat_robot_server]
url = "https://yxj101.cn"